[package]
name = "stratum"
version = "0.1.0"
authors = ["nanpuyue <nanpuyue@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_json = "1.0"
serde_derive = "1.0.80"
ring = "0.13.5"
bytes = { version = "0.4", features = ["serde"] }