[package]
name = "stratum"
version = "0.1.0"
authors = ["nanpuyue <nanpuyue@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ring = "0.13.5"
bytes = { version = "0.4", features = ["serde"] }
num-bigint = "0.2.2"
