[package]
name = "stratum"
version = "0.1.0"
authors = ["nanpuyue <nanpuyue@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = { version = "0.4", features = ["serde"] }
num-bigint = "0.2.2"
tokio = "0.1.14"
tokio-serial = "3.1.0"
tokio-codec = "0.1.1"
lazy_static = "1.2.0"
futures = "0.1.25"
crc = { git = "https://github.com/nanpuyue/crc" }
sha256 = { git = "https://github.com/nanpuyue/sha256" }
